config/routes.rb
Rails.application.routes.draw do
  devise_for :bloggers
  root to: 'articles#index'
  resources :articles
  # get 'articles', to: 'articles#index', as: 'articles'
  # get 'articles/new', to: 'articles#new', as: 'new_article'
  # get 'articles/:id/edit', to: 'articles#edit', as: 'edit_article'
  # get 'articles/:id', to: 'articles#show', as: 'article'
  # post 'articles/create', to: 'articles#create'
  # delete 'articles/:id', to: 'articles#destroy'
  # put 'article/:id', to: 'articles#update'
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, :subtitle, :content, presence: true
  validates :subtitle, length: {maximum: 60}
  validates :title, length: {maximum: 60}
  # scope :list_all_articles, -> { all }
end

app/models/blogger.rb
class Blogger < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles
  validates :first_name, :last_name, :email, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def index
		@articles = Article.page(params[:page])
	end

	def show
		@article = Article.find(params[:id])
	end
	 
	def new
		@article = Article.new
	end

	def create
		@article = Article.new(params.require(:article).permit(:title, :subtitle, :content, :user_id))
		if @article.save
			redirect_to articles_path
		else
			render 'new'
		end
	end

	def edit
	end

	def update
	end

	def destroy
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params.require(:user).permit(:first_name, :last_name, :email, :mobile))
    if @user.save
      redirect_to articles_path
    else
      render 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article do |f| %>
    <div class="mb-3">
        <%= f.hidden_field :user_id, value: current_blogger.id %>
    </div>
    <div class="mb-3">
        <%= f.text_field :title, class: 'form-control', placeholder: 'Title' %>
    </div>
    <div class="mb-3">
        <%= f.text_field :subtitle, class: 'form-control', placeholder: 'Subtitle' %><br/>
    </div>
    <div class="mb-3">
        <%= f.text_area :content, class: 'form-control', rows: '10', placeholder: 'Write your story' %><br/>
    </div>
    <div class="mb-3">
        <%= f.submit 'Publish', class: 'btn btn-outline-dark' %>
    </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit your article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<div class = 'row'>
  <% @articles.each do |article| %> 
    <div class="card border-light mb-3 shadow" style="max-width: 18rem; margin-right: 50px;">
      <div class="card-header"><em>Written by:</em> <%= article.user.first_name.capitalize %></div>
      <div class="card-body">
        <h5 class="card-title"><%= article['title'] %></h5>
        <p class="card-text"><%= article['subtitle'] %></p>
        <%= link_to 'Read', article_path(article['id']), class: 'btn btn-outline-dark' %>
      </div>
    </div> 
  <% end %>
  <p>
    <%= paginate @articles, theme: 'twitter-bootstrap-4' %>
  </p>
</div>

app/views/articles/new.html.erb
<h1>Write a new article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1 style = "font-size: 60px;"><%= @article.title %></h1>
<p style = "text-align:center;"><em><%= @article.subtitle %></em></p>
<p style = "text-align:center;">Written by: <%= link_to @article.user.first_name.capitalize, user_path(@article.user_id) %></p>
<div class = "content">
    <%= @article.content %>
</div>

app/views/layouts/_devise_flash.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_nav.html.erb
<nav class="navbar sticky-top navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Monochrome", root_path, class: 'navbar-brand', style: 'font-size:30px;' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if signed_in? %>
          <li class="nav-item">
            <%= link_to 'Write an article', new_article_path, class: 'nav-link active' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign out', destroy_blogger_session_path, method: :delete, class: 'nav-link active' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign in', new_blogger_session_path, class: 'nav-link active' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Monochrome</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:ital,wght@1,300&display=swap" rel="stylesheet">  
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;400&family=Poppins:wght@900&display=swap" rel="stylesheet"> 
    <link href="https://fonts.googleapis.com/css2?family=Cinzel+Decorative&family=Fredericka+the+Great&family=Press+Start+2P&family=Zilla+Slab+Highlight:wght@700&display=swap" rel="stylesheet">   
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <div class = 'container'>
      <%= render 'layouts/devise_flash' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_with model: @user do |f| %>
    <div class="mb-3">
        <%= f.text_field :first_name, class: 'form-control', placeholder: 'First Name' %>
    </div>
    <div class="mb-3">
        <%= f.text_field :last_name, class: 'form-control', placeholder: 'Last Name' %>
    </div>
    <div class="mb-3">
        <%= f.text_field :email, class: 'form-control', placeholder: 'Email' %><br/>
    </div>
    <div class="mb-3">
        <%= f.text_field :mobile, class: 'form-control', rows: '10', placeholder: 'Mobile Number' %><br/>
    </div>
    <div class="mb-3">
        <%= f.submit 'Sign Up', class: 'btn btn-outline-dark' %>
    </div>
<% end %>

app/views/users/show.html.erb
<h1 style = "font-family: 'Zilla Slab Highlight', cursive;">User Profile</h1>
<div class="card text-white bg-dark mb-3" style="max-width: 30rem; height: 25rem;">
<div class="card-header profile-name"><tt><%= @user.first_name.capitalize %> <%= @user.last_name.capitalize %></tt></div>
<div class="card-body">
<h5 class="card-title">E-mail: <tt><em><%= @user.email %></em></tt></h5>
<h5 class="card-title">Mobile: <tt><em><%= @user.mobile %></em></tt></h5>
</div>
</div>

<div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                  <th scope="col">Article</th>
                  <th scope="col">Subtitle</th>
                  <th scope="col">Action</th>
                  <th scope="col">Written on</th>
                </tr>
              </thead>
              <tbody>
              <% @user.articles.each do |article| %>
                <tr>
                  <th scope="row"><%= article.title %></th>
                  <td><%= article.subtitle %></td>
                  <td><%= link_to 'Read', article_path(article), class:'btn btn-outline-dark'%></td>
                  <td><%= article.created_at %></td>
                </tr>
              <% end %>
              </tbody>
        </table>
</div>